SYNONYMS = {
    "beef": "kød",
    "cheeseburger": "burger",
    "cherry tomato": "tomat",
    "fried chicken": "kylling",
    "greek yogurt": "yoghurt",
    "iceberg": "salat",
    "macaroni": "pasta",
    "mandarin": "appelsin",
    "oatmeal": "havregryn",
    "plantain": "banan",
    "ramen": "nudler",
    "salmon": "laks",
    "steak": "bøf",
    "soda": "cola",
    "rice": "ris",
    "egg": "æg",
    "scrambled egg": "æg",
    "boiled egg": "æg",
    "spaghetti": "pasta",
    "meatball": "kød",
    "hamburger": "burger",
    "lettuce": "salat",
    "carrot": "gulerod",
    "potato": "kartoffel",
    "fries": "pommes frites",
    "orange": "appelsin",
    "grape": "vindrue",
    "apple": "æble",
    "pear": "pære",
    "ketchup": "tomat",
    "bacon": "svinekød",
    "sausage": "pølse",
    "corn": "majs",
    "cucumber": "agurk",
    "onion": "løg",
    "chili": "peberfrugt",
    "chocolate": "chokolade",
    "croissant": "brød",
    "bread": "brød",
    "pita": "brød",
    "wrap": "brød",
    "pizza": "pizza",
    "bowl": "skål",
    "sandwich": "brød",
    "mayonnaise": "dressing"
}
