SYNONYMS = {
    "apple pie": "tærte",
    "baby carrot": "gulerod",
    "beef": "kød",
    "bell pepper": "peberfrugt",
    "boiled egg": "æg",
    "bratwurst": "pølse",
    "broccolini": "broccoli",
    "butter": "smør",
    "canned tuna": "tun",
    "cheddar": "ost",
    "cheeseburger": "burger",
    "cherry tomato": "tomat",
    "chicken soup": "suppe",
    "chicken wrap": "wrap",
    "club sandwich": "sandwich",
    "crepe": "pandekage",
    "cucumber": "agurk",
    "cupcake": "kage",
    "drumstick": "kylling",
    "fried chicken": "kylling",
    "fries": "pommes frites",
    "greek yogurt": "yoghurt",
    "green apple": "æble",
    "iceberg": "salat",
    "lasagna": "lasagne",
    "macaroni": "pasta",
    "mandarin": "appelsin",
    "mashed potato": "kartoffel",
    "meatball": "frikadelle",
    "oatmeal": "havregryn",
    "orange juice": "juice",
    "plantain": "banan",
    "ramen": "nudler",
    "red grapes": "druer",
    "rice porridge": "grød",
    "romaine": "salat",
    "salmon": "fisk",
    "slice of pizza": "pizza",
    "spaghetti": "pasta",
    "steak": "kød",
    "stir fry": "wok",
    "vanilla ice cream": "is",
    "white rice": "ris",
    "whole milk": "mælk",
}
